version: '2'
services:

  # nodejs:
  #   build:
  #     context: ./nodejs
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5555:5555
  #   env_file:
  #     - .env

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
    - .env