version: '2'
services:

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
    - .env

#   nodejs:
#     build:
#       context: ./nodejs
#       dockerfile: Dockerfile
#     ports:
#       - 5555:5555
#     env_file:
#       - .env

# react:
#   build:
#     context: ./reactt
#     dockerfile: Dockerfile
#   ports:
#     - 3000:3000
#   env_file:
#     - .env
